    <fieldset class="fieldset file-upload">
    <div class="field customer_file_upload">
        <label for="customer_image" class="label"><span><?= /* @escapeNotVerified */ __('Customer Image') ?></span></label>
        <div class="control">
            <input type="file" name="customer_image" id="customer_image" title="<?= /* @escapeNotVerified */ __('Custom Image') ?>" class="input-text" data-validate="{required:false}">
        </div>
    </div>
    </<fieldset>